# Generated by Django 5.2.4 on 2025-08-12 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Schedule",
        ),
    ]
