# Generated by Django 5.2.4 on 2025-08-12 05:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_delete_schedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="teacher",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="timeslot",
        ),
        migrations.RemoveField(
            model_name="timeslot",
            name="teacher",
        ),
        migrations.AddField(
            model_name="subject",
            name="website_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="available_for_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teachers",
                to="chatbot.subject",
            ),
        ),
        migrations.CreateModel(
            name="TeacherAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="chatbot.teacher",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.DeleteModel(
            name="Booking",
        ),
        migrations.DeleteModel(
            name="TimeSlot",
        ),
    ]
