# Generated by Django 5.2.4 on 2025-08-12 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_remove_booking_teacher_remove_booking_timeslot_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="available_for_online",
        ),
        migrations.AlterField(
            model_name="teacher",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chatbot.subject"
            ),
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_slot", models.CharField(max_length=100)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot.teacher",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="TeacherAvailability",
        ),
    ]
